export const CREATE_MOVIE = "CREATE_MOVIE";
export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIE = "GET_MOVIE";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_NEXT_PAGE = "SET_NEXT_PAGE";
export const SET_PREVIOUS_PAGE = "SET_PREVIOUS_PAGE";
export const SET_SEARCH_PARAM = "SET_SEARCH_PARAM";
export const SET_FILTER_PARAM = "SET_FILTER_PARAM";
export const CREATE_MOVIE_REACTION = "CREATE_MOVIE_REACTION";
export const CREATE_COMMENT = "CREATE_COMMENTS";
export const GET_COMMENTS_ACTION = "GET_COMMENTS_ACTION";
export const SET_CURRENT_COMMENT_PAGE = "SET_CURRENT_COMMENT_PAGE";
export const SET_COMMENTS_ACTION = "SET_COMMENTS_ACTION";
export const SET_NEXT_COMMENT_PAGE = "SET_NEXT_COMMENT_PAGE";
export const CREATE_WATCHLIST_ACTION = "CREATE_WATCHLIST_ACTION";
export const SET_CURRENT_WATCHLIST_FLAG = "SET_CURRENT_WATCHLIST_FLAG";

export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const SET_POPULAR_MOVIES = "SET_POPULAR_MOVIES";
export const GET_RELATED_MOVIES = "GET_RELATED_MOVIES";
export const SET_RELATED_MOVIES = "SET_RELATED_MOVIES";
export const SET_NEW_COMMENT = "SET_NEW_COMMENT";

